server:
  port: 8080
  address: 127.0.0.1
aefi-to-e2b:
  dhis2:
    mapping:
      program: EZkN8vYZwjR
      vaccine1_name: uSVcZzSM3zg
      vaccine1_brand: JSd0HQOgJ8w
      vaccine1_date: dOkuCjpD978
      vaccine1_time: BSUncNBb20j
      vaccine1_batch: LNqkAlvGplL
      vaccine1_dose: LIyV4t7eCfZ
      vaccine1_expiry: VFrc8SNFYm7
      diluent1_name: xk9QvZPMVQF
      diluent1_batch: FQM2ksIQix8
      diluent1_expiry: cKx0VCmLrsc
      diluent1_dor: om7AsREDduc
      diluent1_tor: zIKVrYHtdUx
      vaccine2_name: g9PjywVj2fs
      vaccine2_brand: eRwc8Y0CNLh
      vaccine2_date: VrzEutEnzSJ
      vaccine2_time: fZFQVZFqu0q
      vaccine2_batch: b1rSwGRcY5W
      vaccine2_dose: E3F414izniN
      vaccine2_expiry: rVUo2PBgwhr
      diluent2_name: WN8844HG0zi
      diluent2_batch: ufWU3WStZgG
      diluent2_expiry: FcqNLPNUPId
      diluent2_dor: xXjnT9sjt4F
      diluent2_tor: KTHsZhIAGWf
      vaccine3_name: OU5klvkk3SM
      vaccine3_brand: wdZrkUvnuyr
      vaccine3_date: f4WCAVwjHz0
      vaccine3_time: VQKdZ1KeD7u
      vaccine3_batch: YBnFoNouH6f
      vaccine3_dose: WlE0K4xCc14
      vaccine3_expiry: ffYfdSPmM1W
      diluent3_name: pLu0luPWikb
      diluent3_batch: MLP8fi1X7UX
      diluent3_expiry: MGjnXmtmd7l
      diluent3_dor: fW6RbpJk4hS
      diluent3_tor: gG0FZYpEctJ
      vaccine4_name: menOXwIFZh5
      vaccine4_brand: Ptms0lmt4QX
      vaccine4_date: H3TKHMFIN6V
      vaccine4_time: S1PRFSk8Y9v
      vaccine4_batch: BHAfwo6JPDa
      vaccine4_dose: Aya8C25DXHe
      vaccine4_expiry: ZfjyIKeX1AN
      diluent4_name: ZTyN8vSf7bc
      diluent4_batch: MyWtDaOdlyD
      diluent4_expiry: qhDonTAIjl0
      diluent4_dor: va0Smpy0LUn
      diluent4_tor: EDdd0HsfLcO
