server:
  port: 8080
  address: 127.0.0.1
aefi-to-e2b:
  dhis2:
    mapping:
      program: EZkN8vYZwjR
      patient_id: h5FuguPFF2j
      patient_gender: CklPZdOd6H1
      patient_given_name: TfdH5KvFmMy
      patient_family_name: aW66s2QSosT
      patient_birthdate: BiTsLcJQ95V
      serious: fq1c1A3EOX5
      seriousness_death: DOA6ZFMro84
      seriousness_death_date: Ze34uXcBUxi
      seriousness_death_autopsy: yRrSDiR5v1M
      seriousness_life_threatening: lATDYNmTLKD
      seriousness_hospitalization: Il1lTfknLdd
      seriousness_disabling: lsO8n8ZmLAB
      seriousness_congenital_anomali: lSBsxcQU0kO
      seriousness_other: tWcNgbkOETR
      seriousness_other_medical_comment: VXdRoWQOBxG
      seriousness_medical_comment: AfrWB2ofm7l
      reporter_name: uZ9c4fKXuNS
      reporter_organization: Q20pEixZxCs
      reporter_comment: IV9W7YXh939
      vaccine1_name: uSVcZzSM3zg
      vaccine1_brand: JSd0HQOgJ8w
      vaccine1_date: dOkuCjpD978
      vaccine1_time: BSUncNBb20j
      vaccine1_batch: LNqkAlvGplL
      vaccine1_dose: LIyV4t7eCfZ
      vaccine1_expiry: VFrc8SNFYm7
      diluent1_name: xk9QvZPMVQF
      diluent1_batch: FQM2ksIQix8
      diluent1_expiry: cKx0VCmLrsc
      diluent1_dor: om7AsREDduc
      diluent1_tor: zIKVrYHtdUx
      vaccine2_name: g9PjywVj2fs
      vaccine2_brand: eRwc8Y0CNLh
      vaccine2_date: VrzEutEnzSJ
      vaccine2_time: fZFQVZFqu0q
      vaccine2_batch: b1rSwGRcY5W
      vaccine2_dose: E3F414izniN
      vaccine2_expiry: rVUo2PBgwhr
      diluent2_name: WN8844HG0zi
      diluent2_batch: ufWU3WStZgG
      diluent2_expiry: FcqNLPNUPId
      diluent2_dor: xXjnT9sjt4F
      diluent2_tor: KTHsZhIAGWf
      vaccine3_name: OU5klvkk3SM
      vaccine3_brand: wdZrkUvnuyr
      vaccine3_date: f4WCAVwjHz0
      vaccine3_time: VQKdZ1KeD7u
      vaccine3_batch: YBnFoNouH6f
      vaccine3_dose: WlE0K4xCc14
      vaccine3_expiry: ffYfdSPmM1W
      diluent3_name: pLu0luPWikb
      diluent3_batch: MLP8fi1X7UX
      diluent3_expiry: MGjnXmtmd7l
      diluent3_dor: fW6RbpJk4hS
      diluent3_tor: gG0FZYpEctJ
      vaccine4_name: menOXwIFZh5
      vaccine4_brand: Ptms0lmt4QX
      vaccine4_date: H3TKHMFIN6V
      vaccine4_time: S1PRFSk8Y9v
      vaccine4_batch: BHAfwo6JPDa
      vaccine4_dose: Aya8C25DXHe
      vaccine4_expiry: ZfjyIKeX1AN
      diluent4_name: ZTyN8vSf7bc
      diluent4_batch: MyWtDaOdlyD
      diluent4_expiry: qhDonTAIjl0
      diluent4_dor: va0Smpy0LUn
      diluent4_tor: EDdd0HsfLcO
      reaction_start_date: vNGUuAZA2C2
      reaction_start_time: NyCB1VAOfJd
      reaction_outcome: yRrSDiR5v1M
      reaction_severe_local_reaction: UNmEidE6M9K
      reaction_above_3_days: We87rvcvd8J
      reaction_beyond_nearest_joint: f8hjxmHOtAB
      reaction_seizures: wCGZpudXuYx
      reaction_seizures_type: Zz4KYO4AsSY
      reaction_abscess: wce39JmsjIK
      reaction_sepsis: tUmgO1Ugv6U
      reaction_encephalopathy: pdpAEuUS1W9
      reaction_toxic_shock_syndrome: Apq4JaueuWR
      reaction_thrombocytopenia: GGLLaieVChK
      reaction_anaphylaxis: MkIgCrCTFyE
      reaction_fever_above_38: rzhHSqK3lQq
      reaction_headache: HY6NIt2FX4A
      reaction_irritability: PWOzcN7UCfW
      reaction_sore_throat: seXW1hERwOo
      reaction_joint_pain: vCfZD893IVe
      reaction_abdominal_pain: T6tsxbKzikz
      reaction_cough: ZdFB8xUhOUM
      reaction_nausea: KOt0J61mF61
      reaction_diarrhoea: NAiZTRCHRWL
      reaction_fatigue: owRcSysyioE
      reaction_vomiting: cMEIyp0rMo1
      reaction_injection_site_soreness: P4oSprWWqrn
      reaction_injection_site_tenderness: KqlCtmOWt4G
      reaction_skin_rash: xgqzqv0p2Us
      reaction_itchingh: FC54HsGMErl
      reaction_muscle_pain: pzOF4lGIyTU
      reaction_persistent_crying: GTyK3p976de
      reaction_poor_breast_feeding: sX1SvRadOmn
      reaction_loss_of_apetite: QFMRugi3fm6
      reaction_chills: TPSvWhUfib3
      reaction_fainting: OhHYABXmGGe
      reaction_mild_fever: nKLO8ZNdR0B
      reaction_tiredness: JaZ9yf1dDy3
      reaction_nasal_congestion: wWDenTQ5xBR
      reaction_lymph_node_enlargement: GEkI9NzxTmM
      reaction_dizziness: XluNAFG1wj6
      reaction_drowsiness: rjjRNU5yDhT
      reaction_other: iTm5wvq16iq
